### ISSUE TITLE
Exercises: Q4 - wrong expected hash?

### ISSUE THREAD

**Issue by joseprsm** [LDSSA/batch2-BLU07#2] opened 2018-06-29 23:09 UTC
Expected hash is the same as Q5, resulting in an Assertion error.

**Comment by PedroMLF** [comment] 2018-07-03 14:54
Thanks for pointing this out. The hash for question 4 is incorrect. This should be fixed this evening.

**Comment by hershaw** [comment] 2018-07-06 14:34
Okay sorry for the delay on this but the fix is now in a PR and should be merged later today. Thanks for the report @joseprsm

**Comment by orlandocosta76** [comment] 2018-07-07 22:08
@hershaw are you sure the new exercises notebook corrected the hash for Q4-b? I mean, if the variable `answer` is supposed to be "the highest value of n, before the most common n-gram starts to be unique?", then it is not working, unless it is something else.

**Comment by hershaw** [comment] 2018-07-09 20:24
I do believe that it is correct. @PedroMLF the fix never got reviewed so it's possible that there is something wrong with it. Can you please take a look at it to make sure the hash is correct? You can check it out in the instructor repo for the BLU and just run the solution to see if it's correct.

**Comment by PedroMLF** [comment] 2018-07-09 21:49
I think that the issue is that we are hashing the variable `answer`, which is used previously and might even pass the assert for most of people. However, we should be using the variable `n`.
The cell should be:

```
expected_hash = '7902699be42c8a8e46fbbb4501726517e86b22c56a189f7625a6da49081b2451'
assert hashlib.sha256(str(n).encode()).hexdigest() == expected_hash
```

(running on my machine)

**Comment by orlandocosta76** [comment] 2018-07-09 23:59
@PedroMLF  the problem is not the name of the variable (one could switch the variable name according to the assert), it's the hashcode itself: the one you have just posted works, which is different from the one in the updated exercise notebook:
```
expected_hash = 'ccd91ce41e7c5ee86b28277dea1cfd1b07f924955f35f7de968aeca4c27e2db8'
assert hashlib.sha256(str(answer).encode()).hexdigest() == expected_hash
```

**Comment by PedroMLF** [comment] 2018-07-10 09:46
In that exercise we are supposed to hash the variable `n`. In the snippet you provided we're hashing the variable `answer`, which exists from a previous question. The goal of this exercise is to get the value of `n` right , not of the variable `answer`. 

The snippet I provided earlier has the hash for the correct value of n. The hash that begins with `cc` refers to the previous value of the `answer` variable, most likely, I'm not sure. However, the goal of the exercise is the value of `n`.

**Comment by orlandocosta76** [comment] 2018-07-10 09:58
@PedroMLF  I understood, what I was saying is that the hashed value does not change because it is stored under variable X ou Y :)

**Comment by hershaw** [comment] 2018-07-10 11:19
@orlandocosta76 can you DM us on slack your answer snippet? then we can check it against our correct solution and give you hints from there.

**Comment by orlandocosta76** [comment] 2018-07-10 11:29
@hershaw I have the correct answer from the start, I was just commenting this issue to let you know the 2nd version of the notebook was not correct for q4-b assert (the hash published here in the issue was the only one that worked, irrespective of the name of the variable which we all know should be **n** and not **answer**).  I suggest you check with @joseprsm if you can close this issue (and maybe correct the exercises notebook with the proper assert)

**Comment by FilipaRodrigues** [comment] 2018-07-16 19:54
I have the same problem. Even though I named the value of n, answer (the variable in the assert) it don't pass the assert:

expected_hash = 'ccd91ce41e7c5ee86b28277dea1cfd1b07f924955f35f7de968aeca4c27e2db8'
assert hashlib.sha256(str(answer).encode()).hexdigest() == expected_hash

I used the one @PedroMLF posted earlier:

expected_hash = '7902699be42c8a8e46fbbb4501726517e86b22c56a189f7625a6da49081b2451'
assert hashlib.sha256(str(n).encode()).hexdigest() == expected_hash

and it worked fine.

**Closed** 2021-03-21 16:10 UTC
